
= JWT & Authentifizierung – Überblick & Snippets
:author: Almina Silnovic & Azra Özdemir
:revdate: 2025-04-14
:toc:
:icons: font

== Was ist JWT?
JWT steht für JSON Web Token. Es ist ein Token, der strukturierte Informationen (sogenannte Claims) enthält und oft für Authentifizierung und Autorisierung verwendet wird.

=== Authentifizierung vs Autorisierung

Authentifizierung: **„Wer bist du?“** – Der Prozess, bei dem ein Benutzer nachweist, wer er ist. Z.B. durch Eingabe von Benutzernamen & Passwort

Autorisierung: **„Was darfst du tun?“** – Der Prozess, bei dem geprüft wird, auf welche Ressourcen der authentifizierte Benutzer zugreifen darf. Z.B. auf welches Bankkonto darfst du zugreifen?

=== Aufbau
Der Token besteht aus drei Base64Url-codierten Teilen, getrennt durch Punkte.

[source]
----
<Header>.<Payload>.<Signature>
----

**Header:**
Gibt den Typ des Tokens und den verwendeten Algorithmus zum Verschlüsseln (Z.B. HS256) an.
[source,json]
----
{
  "alg": "HS256",
  "typ": "JWT"
}
----

**Payload:**
Enthält die Claims, also die eigentlichen Daten wie Benutzer-ID oder Rollen, die übertragen werden sollen.
[source,json]
----
{
  "sub": "1234567890",
  "name": "Max Mustermann",
  "iat": 1713436800,
  "exp": 1713440400,
  "admin": true
}
----

**Signature:**
Dient zur Überprüfung der Echtheit des Tokens, indem sie aus Header, Payload und einem geheimen Schlüssel erzeugt wird.
[source]
----
HMACSHA256(
  base64UrlEncode(header) + "." + base64UrlEncode(payload),
  geheim_schlüssel
)
----

== Ablauf: Auth mit JWT

1. User loggt sich ein: Der Benutzer schickt einen Request mit POST an den Server, der die Anmeldedaten enthält.
2. Server gibt JWT zurück: Nach erfolgreicher Anmeldung erstellt der Server ein JWT und schickt eine Response an den Client.
3. Client speichert Token: Der Client speichert das JWT, um es später zu verwenden.
4. Client sendet Token mit: Bei weiteren Requests schickt der Client das JWT an den Server.
5. Server prüft Token: Der Server prüft das JWT, indem er...
    - die Signatur validiert **(wurden die Daten verändert?)**,
    - das Ablaufdatum prüft **(ist der Token noch gültig und nicht abgelaufen?)**

Wenn alles passt, gewährt der Server Zugriff.

== Vorteile und Nachteile
Alternativen nennen (Sessions), wann sollte man was verwenden?...

== weitere Code-Snippets

JWT erstellen:

weiteres
...